/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ac.itcr.perez_moya.datos1.gui;

import ac.itcr.perez_moya.datos1.library.Book;
import ac.itcr.perez_moya.datos1.library.Library;
import ac.itcr.perez_moya.datos1.library.LibraryManager;
import ac.itcr.perez_moya.datos1.library.Topic;
import java.util.Collection;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samoy
 */
public class BookSearch extends javax.swing.JFrame {
    
    private Book book;

    public Book getBook() {
        return book;
    }
    /**}
     * Creates new form BookSearch
     */
    public BookSearch() {
        initComponents();

        this.librariesCombo.addItem("Librerías");
        for (Library library : LibraryManager.getInstance().getLibrarys()) {
            librariesCombo.addItem(library.getNameLib());
        }

        this.themeCombo.addItem("Tema");
        for (Topic topic : Topic.values()) {
            themeCombo.addItem(topic.name());
        }
    }

    private void refreshBooks() {

        String libraryName = (String) librariesCombo.getSelectedItem();
        if (librariesCombo.getSelectedIndex() == 0) {
            libraryName = null;
        }

        String topicName = (String) themeCombo.getSelectedItem();
        if (themeCombo.getSelectedIndex() == 0) {
            topicName = null;
        }

        Book newBook = new Book();
        newBook.setTopic(topicName);
        String name = booksName.getText();
        newBook.setName(name);

        DefaultTableModel model = ((DefaultTableModel) bookstable.getModel());
        model.setRowCount(0);
        for (Book book : LibraryManager.getInstance().search(newBook)) {
            model.addRow(new Object[]{
                book.getIssn(), book.getName(), book.getTopic(), book.getPrice(), book.getSoldBooks(), book.getAvailableBooks()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        librariesCombo = new javax.swing.JComboBox<>();
        themeCombo = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        orderBotton = new javax.swing.JButton();
        detailBotton = new javax.swing.JButton();
        booksName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookstable = new javax.swing.JTable();
        shoppingCar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        shoppingList = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        librariesCombo.setName(""); // NOI18N
        librariesCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librariesComboActionPerformed(evt);
            }
        });

        themeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themeComboActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Precios" }));

        jLabel1.setText("Nombre de libro:");

        orderBotton.setText("Ordenar");
        orderBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderBottonActionPerformed(evt);
            }
        });

        detailBotton.setText("Ver detalle");
        detailBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailBottonActionPerformed(evt);
            }
        });

        booksName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksNameActionPerformed(evt);
            }
        });

        bookstable.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bookstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ISSN", "Nombre", "Tema", "Precio", "Cantidad Vendida", "Cantidad Disponible"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(bookstable);

        shoppingCar.setText("Agragar al carrito");
        shoppingCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shoppingCarActionPerformed(evt);
            }
        });

        shoppingList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Comprar"
            }
        ));
        jScrollPane1.setViewportView(shoppingList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(librariesCombo, 0, 341, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(themeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(booksName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addComponent(shoppingCar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(orderBotton, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(detailBotton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(librariesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(themeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(booksName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(detailBotton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(shoppingCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void librariesComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librariesComboActionPerformed

        refreshBooks();

        // TODO add your handling code here:
    }//GEN-LAST:event_librariesComboActionPerformed

    private void orderBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderBottonActionPerformed

        ClientInfo infoc = new ClientInfo();
        infoc.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_orderBottonActionPerformed

    private void detailBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailBottonActionPerformed
        Object detail = this.bookstable.getValueAt(this.bookstable.getSelectedRow(), this.bookstable.getSelectedColumn());
        BookDetail bookd = new BookDetail();        // TODO add your handling code here:
        bookd.setVisible(true);
    }//GEN-LAST:event_detailBottonActionPerformed

    private void booksNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksNameActionPerformed
        refreshBooks();
    }//GEN-LAST:event_booksNameActionPerformed

    private void themeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themeComboActionPerformed
        refreshBooks();
// TODO add your handling code here:
    }//GEN-LAST:event_themeComboActionPerformed

    private void shoppingCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shoppingCarActionPerformed
        DefaultTableModel model = (DefaultTableModel) shoppingList.getModel();
        model.addRow(new Object[]{
            this.bookstable.getValueAt(this.bookstable.getSelectedRow(), 1)
        });
//shoppingList.append((String) this.bookstable.getValueAt(this.bookstable.getSelectedRow(), this.bookstable.getSelectedColumn()));
        refreshBooks();
//LibraryManager.getInstance().addBook(this.bookstable.getSelectedRow());        // TODO add your handling code here:
    }//GEN-LAST:event_shoppingCarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField booksName;
    private javax.swing.JTable bookstable;
    private javax.swing.JButton detailBotton;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> librariesCombo;
    private javax.swing.JButton orderBotton;
    private javax.swing.JButton shoppingCar;
    private javax.swing.JTable shoppingList;
    private javax.swing.JComboBox<String> themeCombo;
    // End of variables declaration//GEN-END:variables
}
